#!/bin/bash

# Cleanup script for unused/redundant files

echo "🧹 Cleaning up unused files..."

# Old deployment docs (redundant)
rm -f "DEPLOY_AI_ORACLE.md"
rm -f "DEPLOY_BACKEND_CLEAN.sh"
rm -f "DEPLOY_CHECKLIST.txt"
rm -f "DEPLOY_FRONTEND_MANUAL.md"
rm -f "DEPLOY_FRONTEND.sh"
rm -f "DEPLOY_MANUAL.txt"
rm -f "DEPLOY_NOW.md"
rm -f "DEPLOY_NOW.sh"
rm -f "DEPLOY_POH_UPDATE.md"
rm -f "DEPLOY_POH_VPS.md"
rm -f "DEPLOY_TO_PRODUCTION.md"
rm -f "deploy-ai-oracle.sh"
rm -f "deploy-backend-vps.sh"
rm -f "deploy-backend.sh"
rm -f "deploy-for-testing.sh"
rm -f "deploy-frontend-auto.sh"
rm -f "deploy-frontend-correct.sh"
rm -f "deploy-frontend-vps.sh"
rm -f "deploy-no-ssh.sh"
rm -f "deploy-now.sh"
rm -f "deploy-passport.sh"
rm -f "deploy-poh-vps.sh"
rm -f "deploy-vps-manual.sh"
rm -f "deploy-vps.sh"
rm -f "DEPLOY.sh"
rm -f "DEPLOYMENT_CHECKLIST.md"
rm -f "DEPLOYMENT_COMPLETE_SUMMARY.md"
rm -f "DEPLOYMENT_NOW.md"
rm -f "DEPLOYMENT_STATUS.md"
rm -f "DEPLOYMENT_SUCCESS.md"
rm -f "DEPLOYMENT_SYNC_REPORT.md"
rm -f "DEPLOYMENT_V2.md"
rm -f "FINAL_DEPLOY.sh"

# Old status/fix docs (redundant)
rm -f "COMPLETE_STATUS.md"
rm -f "FINAL_FIX_POH.md"
rm -f "FINAL_FIX.md"
rm -f "FINAL_SOLUTION.md"
rm -f "FINAL_SYSTEM_REPORT.md"
rm -f "FIX_APPLIED.md"
rm -f "FIX_BACKEND_SERVICE.sh"
rm -f "fix-nginx-port.sh"
rm -f "fix-nginx-routing.sh"
rm -f "fix-vps-deployment.sh"
rm -f "LOCALHOST_FIX_SUMMARY.md"
rm -f "RESTORE_GOOD_VERSION.md"
rm -f "SSH_FIX.md"
rm -f "STATUS_CHECKLIST.md"
rm -f "VISUAL_STATUS.txt"

# Old phase docs (redundant)
rm -f "GELOMBANG2_COMPLETE.md"
rm -f "GELOMBANG2_FINAL_STATUS.md"
rm -f "GELOMBANG2_ROADMAP.md"
rm -f "GELOMBANG2_STATUS.md"
rm -f "PHASE_STATUS_REPORT.md"
rm -f "PHASE_VERIFICATION_REPORT.md"
rm -f "PHASE1_COMPLETE.md"
rm -f "PHASE2_COMPLETE_SUMMARY.md"
rm -f "PHASE2_COMPLETE.md"
rm -f "PHASE2_DEPLOY.md"
rm -f "PHASE2_TESTING_DEPLOYMENT.md"
rm -f "PHASE3_COMPLETE_SUMMARY.md"

# Old test docs (redundant)
rm -f "POH_SETUP_GUIDE.md"
rm -f "POH_TEST_GUIDE.md"
rm -f "POH_TESTING_CHECKLIST.md"
rm -f "QUICK_DEPLOY_TESTING.md"
rm -f "QUICK_DEPLOY.md"
rm -f "QUICK_START_POH.md"
rm -f "QUICK_START.md"
rm -f "QUICK_TEST_GUIDE.md"
rm -f "QUICK_TEST.md"
rm -f "RUN_PHASE2_TEST.md"
rm -f "TEST_LOCAL.md"
rm -f "TEST_OAUTH.md"
rm -f "test_result.md"
rm -f "TEST_RESULTS_SUMMARY.md"
rm -f "TEST_RESULTS.md"
rm -f "USER_TESTING_CHECKLIST.md"
rm -f "USER_TESTING_DEPLOYMENT.md"

# Old frontend/integration docs (redundant)
rm -f "FRONTEND_DEPLOYMENT.md"
rm -f "FRONTEND_INTEGRATION_COMPLETE.md"
rm -f "FRONTEND_ONCHAIN_ANALYSIS.md"
rm -f "FRONTEND_TEST_CHECKLIST.md"
rm -f "INTEGRATION_GUIDE.md"
rm -f "INTEGRATION_SUMMARY.md"
rm -f "LOCAL_PROJECT_SUMMARY.md"
rm -f "PROJECT_STATUS.md"

# Old OAuth/Cloudflare docs (redundant)
rm -f "CLOUDFLARE_DEV_MODE.md"
rm -f "CLOUDFLARE_PURGE.md"
rm -f "GITHUB_OAUTH_FIX.md"
rm -f "OAUTH_DEBUG.md"
rm -f "OAUTH_SETUP_QUICK.md"
rm -f "PURGE_CLOUDFLARE.md"

# Old VPS/check scripts (redundant)
rm -f "bypass_cloudflare.sh"
rm -f "check-all-phases.sh"
rm -f "check-backend-location.sh"
rm -f "check-deployment-sync.sh"
rm -f "check-frontend-vps.sh"
rm -f "check-onchain-badges.sh"
rm -f "check-passport-api.sh"
rm -f "check-passport-data.sh"
rm -f "update-frontend-vps.sh"
rm -f "VPS_HEALTH_CHECK.sh"
rm -f "VPS_UPDATE_INSTRUCTIONS.md"
rm -f "VERIFY_PORT_9000.md"

# Old test scripts (redundant)
rm -f "create-passport-test.sh"
rm -f "DETAILED_ENDPOINT_TEST.sh"
rm -f "force-create-passport.sh"
rm -f "restart-and-test.sh"
rm -f "test-all-endpoints.sh"
rm -f "test-api-complete.sh"
rm -f "test-api.sh"
rm -f "test-backend-start.sh"
rm -f "test-fast-api.sh"
rm -f "test-phase2.sh"
rm -f "test-poh-production.sh"
rm -f "test-poh.sh"
rm -f "TEST_ALL_FEATURES.sh"
rm -f "verify_backend.sh"

# Old HTML test files
rm -f "check-api.html"
rm -f "TEST_DIRECT.html"
rm -f "test-oauth-url.html"

# Old start scripts (keep only active ones)
rm -f "START_FRONTEND.sh"
rm -f "START_HERE.md"
rm -f "START_LOCAL_BROWSER.sh"
rm -f "START_LOCAL.sh"
rm -f "start-backend.sh"
rm -f "start-port-8080.sh"
rm -f "start-with-blockchain.sh"

# Old misc files
rm -f "add-key.sh"
rm -f "backend.pid"
rm -f "nginx-redirect.conf"
rm -f "setup-oauth-credentials.sh"
rm -f "aura-backend.service"

# Redundant analytics docs (keep only final)
rm -f "LIVE_ANALYTICS_FEATURE.md"

# Redundant API docs (keep only final)
rm -f "API_INTEGRATION_STATUS.md"
rm -f "QUICK_API_TEST.md"

# Redundant contract docs (keep only main)
rm -f "CREDIT_PASSPORT_DEPLOYED.md"
rm -f "ONCHAIN_ANALYSIS.md"

# Redundant misc docs
rm -f "AUTHORIZE_USERS.md"
rm -f "MINTING_GUIDE.md"
rm -f "PROJECT_DOCUMENTATION.md"
rm -f "SECURITY_CHECKLIST.md"
rm -f "SETUP_PRIVATE_KEY.md"
rm -f "USER_MINT_GUIDE.md"
rm -f "VERCEL_DEPLOYMENT.md"

echo "✅ Cleanup complete!"
echo "📊 Kept essential files:"
echo "  - README.md (main)"
echo "  - AURA_PROTOCOL_DATA_FLOW.md (complete guide)"
echo "  - API_ONCHAIN_INTEGRATED.md (API docs)"
echo "  - SMART_CONTRACTS_OVERVIEW.md (contracts)"
echo "  - OAUTH_LOCAL_SETUP.md (OAuth setup)"
echo "  - RUNNING_NOW.md (current status)"
echo "  - start-fast-backend.sh (active)"
echo "  - start-frontend-3030.sh (active)"
